[package]
name = "pulpit-server"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "pulpit-server"
path = "src/main.rs"

[dependencies]
anyhow = "1"
dirs = "5"
serde_json = { workspace = true }
tokio = { workspace = true }
axum = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
pulpit-db = { path = "../../crates/db" }
pulpit-host = { path = "../../crates/host" }
pulpit-proto = { path = "../../crates/proto" }
pulpit-backend = { path = "../../crates/backend" }
pulpit-legacy = { path = "../../crates/legacy" }
pulpit-v2 = { path = "../../crates/v2" }
pulpit-ext = { path = "../../crates/ext" }
pulpit-vm = { path = "../../crates/vm" }
pulpit-discord = { path = "../../crates/discord" }
pulpit-spotify = { path = "../../crates/spotify" }
pulpit-os = { path = "../../crates/os" }
pulpit-sysinfo = { path = "../../crates/sysinfo" }
pulpit-aidev = { path = "../../crates/aidev" }
