[package]
name = "pulpit-discord"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
ureq = "3"
pulpit-db = { path = "../db" }

[dev-dependencies]
tempfile = "3"
