[package]
name = "pulpit-tools"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
pulpit-db = { path = "../db" }
pulpit-actions = { path = "../actions" }
pulpit-os = { path = "../os" }
pulpit-legacy = { path = "../legacy" }

[dev-dependencies]
tempfile = "3"
