[package]
name = "pulpit-backend"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde_json = { workspace = true }
tracing = { workspace = true }
pulpit-db = { path = "../db" }
pulpit-actions = { path = "../actions" }
pulpit-legacy = { path = "../legacy" }
pulpit-ext = { path = "../ext" }
pulpit-vm = { path = "../vm" }
pulpit-discord = { path = "../discord" }
pulpit-spotify = { path = "../spotify" }
pulpit-os = { path = "../os" }
pulpit-tools = { path = "../tools" }
pulpit-sysinfo = { path = "../sysinfo" }
pulpit-aidev = { path = "../aidev" }
ureq = "3"

[dev-dependencies]
tempfile = "3"
