// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Board background: flat color or a hashed asset (image).
 */
export type Background = { "kind": "color", color: string, } | { "kind": "asset", hash: string, };
