// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Board } from "./Board";

/**
 * Full snapshot pushed after `welcome` and whenever the editor replaces
 * board data wholesale (import).
 */
export type BoardsSync = { generation: number, boards: Array<Board>, };
