// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BoardOp } from "./BoardOp";

/**
 * Live board change batch; broadcast to all clients. Clients that miss
 * deltas (reconnect) recover via `boards.sync`.
 */
export type BoardsDelta = { generation: number, ops: Array<BoardOp>, };
