// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Background } from "./Background";
import type { Tile } from "./Tile";

/**
 * Board-level v2 struct: a grid plus free-placement tiles.
 */
export type Board = { id: bigint, name: string, width: number, height: number, order: number, background: Background | null, tiles?: Array<Tile>, };
