// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Server directive to show a board (a `board` command executed). Purely
 * UI: board data itself only flows through sync/delta.
 */
export type BoardOpen = { board: bigint, };
