// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Board } from "./Board";
import type { Tile } from "./Tile";

/**
 * One committed board change. `tile-set` always carries the full tile,
 * which covers add, style edit and move/resize alike.
 */
export type BoardOp = { "op": "board-set", board: Board, } | { "op": "board-remove", board: bigint, } | { "op": "tile-set", board: bigint, tile: Tile, } | { "op": "tile-remove", board: bigint, tile: bigint, } | { "op": "tile-clear", board: bigint, };
