// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StateShape } from "./StateShape";

/**
 * One live state channel in the `welcome` catalog: how to render its
 * values and (for series) the server's ring-buffer size.
 */
export type ChannelInfo = { shape: StateShape, cap: number | null, };
