// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * One channel value in a patch batch. For series channels `value` is the
 * newest point (clients append).
 */
export type ChannelValue = { channel: string, value: JsonValue, };
