// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * One event frame on the v2 WebSocket. Requests carry `id`; responses
 * echo it back as `ack`.
 */
export type Frame = { v: number, id: string | null, ack: string | null, type: string, payload?: JsonValue | null, };
