// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Interaction } from "./Interaction";
import type { InteractionArgs } from "./InteractionArgs";

/**
 * Client -> server user gesture on a tile.
 */
export type InteractionPayload = { board: bigint, tile: bigint, interaction: Interaction, args: InteractionArgs, };
