// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * User interactions a widget accepts (declared in the manifest so the
 * client knows which gestures to grab).
 */
export type Interaction = "tap" | "press-start" | "press-end" | "slide" | "long-press" | "double-tap" | "swipe-left" | "swipe-right" | "wheel" | "drag" | "other";
