// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-gesture arguments. Only the field matching the interaction kind is
 * meaningful (`slide` -> `value`, `wheel` -> `delta`, `drag` -> `dx/dy`).
 */
export type InteractionArgs = { value: number | null, delta: number | null, dx: number | null, dy: number | null, };
