// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Free placement inside a board grid (pixel-space of the 96px cell grid).
 */
export type Placement = { x: number, y: number, w: number, h: number, };
