// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelValue } from "./ChannelValue";

/**
 * Coalesced state updates, flushed every 100 ms, latest wins per channel.
 */
export type StatePatch = { changes: Array<ChannelValue>, };
