// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Full current state, pushed once after `welcome`. Series arrays run
 * oldest -> newest.
 */
export type StateSync = { values?: { [key in string]: JsonValue }, series?: { [key in string]: Array<number> }, };
