// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StateShape } from "./StateShape";

export type StateRef = { channel: string, shape: StateShape, };
