// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Style = { color: string | null, color2: string | null, 
/**
 * FontAwesome glyph as a unicode character (already resolved).
 */
icon: string | null, title: string | null, shape: string | null, };
