// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Style = { color: string | null, 
/**
 * State-dependent colors: `color2` shows while the tile's channel is
 * in its active state.
 */
color2: string | null, 
/**
 * FontAwesome glyph as a unicode character (already resolved).
 */
icon: string | null, 
/**
 * Active-state glyph (e.g. mic -> mic-slash); paired with `color2`.
 */
icon2: string | null, 
/**
 * Font family for the glyphs: `"fas"` (default) or `"fab"` (brands).
 */
icon_family: string | null, title: string | null, shape: string | null, 
/**
 * Tile border color; clients render a hairline border when set.
 */
border_color: string | null, 
/**
 * Active-state border (per-field fallback to `border_color`, §4).
 */
border_color2: string | null, 
/**
 * Glyph color; defaults to white client-side when absent.
 */
icon_color: string | null, 
/**
 * Active-state glyph color (per-field fallback to `icon_color`, §4).
 */
icon_color2: string | null, 
/**
 * Title text color; defaults to white client-side when absent.
 */
title_color: string | null, 
/**
 * Active-state title color (per-field fallback to `title_color`, §4).
 */
title_color2: string | null, };
