// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One tile: placement + manifest flattened into a single object.
 */
export type Tile = Placement & WidgetManifest;
