// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelInfo } from "./ChannelInfo";
import type { Device } from "./Device";

export type Welcome = { protocol: number, desktop_version: string, 
/**
 * Clients below this version are closed with `outdated-client`.
 */
min_client: string, 
/**
 * Board generation; grows by one per committed write batch.
 */
generation: number, device: Device, 
/**
 * The device token, carried ONLY in the welcome that completes a
 * pairing (the client stores it and authenticates with it later).
 * Token reconnects omit it.
 */
token: string | null, channels?: { [key in string]: ChannelInfo }, };
