// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelInfo } from "./ChannelInfo";
import type { Device } from "./Device";

export type Welcome = { protocol: number, desktop_version: string, 
/**
 * Clients below this version are closed with `outdated-client`.
 */
min_client: string, 
/**
 * Board generation; grows by one per committed write batch.
 */
generation: number, device: Device, channels?: { [key in string]: ChannelInfo }, 
/**
 * The device token, issued only in the welcome that completes a
 * pairing (docs/protocol-v2.md §3 step 4); reconnecting devices know
 * it already.
 */
token?: string | null, };
