// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Widget kinds the client knows how to render. New kinds are additive:
 * older clients fall back to `Button`.
 */
export type WidgetKind = "button" | "toggle" | "slider" | "knob" | "graph" | "list" | "web" | "photo" | "video" | "other";
