// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Interaction } from "./Interaction";
import type { StateRef } from "./StateRef";
import type { Style } from "./Style";
import type { WidgetKind } from "./WidgetKind";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Declarative widget manifest stored inside a board layout.
 */
export type WidgetManifest = { kind: WidgetKind, params: JsonValue, 
/**
 * State channel this widget reads (e.g. `"vm.volume"`), with shape.
 */
state: StateRef | null, interactions?: Array<Interaction>, style: Style | null, 
/**
 * Web widgets only: package id of the HTML bundle to render.
 */
web_package: string | null, 
/**
 * Content hash of the tile's image asset (button image, photo,
 * video), served from `/assets/<hash>`.
 */
asset_hash: string | null, };
