[package]
name = "deckboard-actions"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
deckboard-os = { path = "../os" }
serde_json = { workspace = true }
tracing = { workspace = true }
enigo = { workspace = true }
thiserror = { workspace = true }
open = { workspace = true }
